import { Adopter } from '../types/adopter';
import { PetWithCompatibility } from '../types/pet';
import { ActiveMatch, StabilitySummary } from '../types/match';
import { VisitSlot } from '../types/visit';
import { TrainingPlan } from '../types/training';
import { DailyCheckIn, WeeklyCheckIn } from '../types/checkin';

export const mockAdopter: Adopter = {
  id: 'adopter-001',
  deviceId: 'mock-device-001',
  zipCode: '90210',
  searchRadius: 25,
  housingType: 'house',
  hoursAwayPerDay: 8,
  activityLevel: 3,
  experienceLevel: 'intermediate',
  hasKids: false,
  hasExistingPets: false,
  barkingTolerance: 3,
  sheddingTolerance: 4,
  trainingCommitment: 4,
  specialNeedsWilling: false,
  narrative1: 'I want a loyal companion for weekend hikes.',
  narrative2: 'I am patient and willing to invest time in training.',
  onboardingComplete: true,
  createdAt: '2026-01-15T10:00:00Z',
  updatedAt: '2026-01-15T10:00:00Z',
};

export const mockPets: PetWithCompatibility[] = [
  {
    id: 'pet-001',
    name: 'Luna',
    breed: 'Golden Retriever',
    age: 'young',
    size: 'large',
    description: 'A friendly and energetic golden who loves outdoor adventures.',
    imageUrls: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600',
      'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600',
    ],
    barkingLevel: 2,
    sheddingLevel: 4,
    trainingLevel: 3,
    energyLevel: 4,
    specialNeeds: false,
    behaviorTraits: ['energetic', 'social', 'playful'],
    promptLabel: 'Best trait',
    promptAnswer: 'Will greet you at the door every single day',
    createdAt: '2026-01-10T10:00:00Z',
    compatibilityScore: 92,
    whyMatch: [
      'Your activity level matches her energy needs',
      'House with yard is perfect for a Golden',
      'Your commitment to training aligns with her needs',
    ],
    potentialChallenges: [
      'Heavy shedding may require frequent grooming',
      'High energy may need 2+ hours of exercise daily',
    ],
    aiSummary:
      'Luna is a joyful golden retriever who thrives with active families. She responds well to positive reinforcement and loves water.',
  },
  {
    id: 'pet-002',
    name: 'Max',
    breed: 'Labrador Mix',
    age: 'adult',
    size: 'large',
    description: 'A gentle lab mix looking for his forever home.',
    imageUrls: [
      'https://images.unsplash.com/photo-1529429617124-95b109e86bb8?w=600',
      'https://images.unsplash.com/photo-1477884213360-7e9d7dcc8f9b?w=600',
    ],
    barkingLevel: 2,
    sheddingLevel: 3,
    trainingLevel: 4,
    energyLevel: 3,
    specialNeeds: false,
    behaviorTraits: ['calm', 'affectionate', 'social'],
    promptLabel: 'Favorite activity',
    promptAnswer: 'Napping on the couch after a long walk',
    createdAt: '2026-01-08T10:00:00Z',
    compatibilityScore: 88,
    whyMatch: [
      'His calm temperament suits your lifestyle',
      'Already well-trained and house-broken',
      'Great with first-time and intermediate owners',
    ],
    potentialChallenges: [
      'May have separation anxiety when left alone',
      'Needs consistent daily walks',
    ],
    aiSummary:
      'Max is a laid-back lab mix who already knows basic commands. He is great with people and adapts easily to new environments.',
  },
  {
    id: 'pet-003',
    name: 'Bella',
    breed: 'Beagle',
    age: 'puppy',
    size: 'medium',
    description: 'An adorable beagle puppy with a curious personality.',
    imageUrls: [
      'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600',
      'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=600',
    ],
    barkingLevel: 4,
    sheddingLevel: 2,
    trainingLevel: 1,
    energyLevel: 4,
    specialNeeds: false,
    behaviorTraits: ['energetic', 'playful', 'social'],
    promptLabel: 'Superpower',
    promptAnswer: 'Can sniff out treats from three rooms away',
    createdAt: '2026-01-12T10:00:00Z',
    compatibilityScore: 74,
    whyMatch: [
      'Your experience level can handle puppy training',
      'Your activity level matches her playful nature',
    ],
    potentialChallenges: [
      'Beagles are vocal - may bark more than you expect',
      'Puppies require significant time investment',
      'Escape artist - needs secure fencing',
    ],
    aiSummary:
      'Bella is a spirited beagle puppy full of curiosity. She will need patient, consistent training but will reward you with endless loyalty.',
  },
  {
    id: 'pet-004',
    name: 'Charlie',
    breed: 'French Bulldog',
    age: 'adult',
    size: 'small',
    description: 'A charming Frenchie who loves snuggles.',
    imageUrls: [
      'https://images.unsplash.com/photo-1583337130417-13219ce0e39f?w=600',
    ],
    barkingLevel: 1,
    sheddingLevel: 2,
    trainingLevel: 3,
    energyLevel: 2,
    specialNeeds: true,
    specialNeedsDescription: 'Needs regular vet checkups for breathing',
    behaviorTraits: ['calm', 'affectionate'],
    promptLabel: 'Life motto',
    promptAnswer: 'Why run when you can waddle?',
    createdAt: '2026-01-09T10:00:00Z',
    compatibilityScore: 81,
    whyMatch: [
      'Low energy suits your work schedule',
      'Apartment-friendly size',
      'Minimal barking is great for neighbors',
    ],
    potentialChallenges: [
      'Special health needs require extra vet visits',
      'Can be stubborn during training',
    ],
    aiSummary:
      'Charlie is a loving French Bulldog who prefers cuddles over cardio. He needs someone aware of brachycephalic health considerations.',
  },
  {
    id: 'pet-005',
    name: 'Daisy',
    breed: 'Border Collie',
    age: 'young',
    size: 'medium',
    description: 'A brilliant border collie looking for a job to do.',
    imageUrls: [
      'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=600',
      'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600',
    ],
    barkingLevel: 3,
    sheddingLevel: 3,
    trainingLevel: 2,
    energyLevel: 5,
    specialNeeds: false,
    behaviorTraits: ['energetic', 'independent', 'playful'],
    promptLabel: 'Dream date',
    promptAnswer: 'An agility course followed by a sunset hike',
    createdAt: '2026-01-11T10:00:00Z',
    compatibilityScore: 69,
    whyMatch: [
      'Your willingness to train is perfect for a collie',
      'Your activity level can partially match hers',
    ],
    potentialChallenges: [
      'Extremely high energy - needs 2+ hours exercise',
      'Can develop behavioral issues if under-stimulated',
      'Herding instinct may be tricky with kids/other pets',
    ],
    aiSummary:
      'Daisy is incredibly smart and needs mental stimulation as much as physical. She excels with owners who enjoy dog sports or long hikes.',
  },
  {
    id: 'pet-006',
    name: 'Cooper',
    breed: 'Australian Shepherd',
    age: 'young',
    size: 'medium',
    description: 'A gorgeous Aussie with stunning blue eyes.',
    imageUrls: [
      'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=600',
    ],
    barkingLevel: 3,
    sheddingLevel: 4,
    trainingLevel: 2,
    energyLevel: 5,
    specialNeeds: false,
    behaviorTraits: ['energetic', 'social', 'protective'],
    promptLabel: 'Hidden talent',
    promptAnswer: 'Can learn a new trick in under 10 minutes',
    createdAt: '2026-01-13T10:00:00Z',
    compatibilityScore: 71,
    whyMatch: [
      'Your training commitment matches his need for structure',
      'Your home type provides needed space',
    ],
    potentialChallenges: [
      'Heavy shedding year-round',
      'Needs a confident, experienced handler',
      'Can be protective around strangers',
    ],
    aiSummary:
      'Cooper is a loyal and intelligent Aussie who bonds deeply with his person. He needs firm but gentle leadership and plenty of activity.',
  },
  {
    id: 'pet-007',
    name: 'Milo',
    breed: 'Cavalier King Charles',
    age: 'senior',
    size: 'small',
    description: 'A sweet senior Cavalier looking for a quiet home.',
    imageUrls: [
      'https://images.unsplash.com/photo-1591160690555-5debfba0c36a?w=600',
    ],
    barkingLevel: 1,
    sheddingLevel: 3,
    trainingLevel: 5,
    energyLevel: 1,
    specialNeeds: true,
    specialNeedsDescription: 'Heart medication required daily',
    behaviorTraits: ['calm', 'affectionate', 'reserved'],
    promptLabel: 'Perfect day',
    promptAnswer: 'Sitting in your lap while you read a book',
    createdAt: '2026-01-07T10:00:00Z',
    compatibilityScore: 77,
    whyMatch: [
      'Very low maintenance exercise needs',
      'Already fully trained',
      'Perfect companion for quiet evenings',
    ],
    potentialChallenges: [
      'Ongoing medical expenses for heart condition',
      'May not keep up on long hikes',
    ],
    aiSummary:
      'Milo is a gentle senior who has so much love left to give. He is perfect for someone who values companionship over activity.',
  },
  {
    id: 'pet-008',
    name: 'Sadie',
    breed: 'German Shepherd',
    age: 'adult',
    size: 'large',
    description: 'A loyal GSD who excels at obedience.',
    imageUrls: [
      'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600',
    ],
    barkingLevel: 3,
    sheddingLevel: 5,
    trainingLevel: 4,
    energyLevel: 4,
    specialNeeds: false,
    behaviorTraits: ['protective', 'calm', 'independent'],
    promptLabel: 'What makes me special',
    promptAnswer: 'I will guard your heart (and your house)',
    createdAt: '2026-01-14T10:00:00Z',
    compatibilityScore: 83,
    whyMatch: [
      'Highly trainable and responds to your commitment',
      'Your home provides the space she needs',
      'Your experience level is suitable',
    ],
    potentialChallenges: [
      'Very heavy shedding requires daily brushing',
      'Can be wary of strangers',
    ],
    aiSummary:
      'Sadie is a devoted German Shepherd who thrives with structure and clear leadership. She is well-trained and incredibly loyal.',
  },
  {
    id: 'pet-009',
    name: 'Rosie',
    breed: 'Poodle Mix',
    age: 'young',
    size: 'small',
    description: 'A hypoallergenic poodle mix with a cheerful disposition.',
    imageUrls: [
      'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=600',
    ],
    barkingLevel: 2,
    sheddingLevel: 1,
    trainingLevel: 3,
    energyLevel: 3,
    specialNeeds: false,
    behaviorTraits: ['playful', 'social', 'affectionate'],
    promptLabel: 'Deal breaker',
    promptAnswer: 'If you do not share your snacks',
    createdAt: '2026-01-06T10:00:00Z',
    compatibilityScore: 86,
    whyMatch: [
      'Minimal shedding matches your preference',
      'Moderate energy fits your lifestyle',
      'Great temperament for any living situation',
    ],
    potentialChallenges: [
      'Requires regular professional grooming',
      'Can be anxious during thunderstorms',
    ],
    aiSummary:
      'Rosie is a delightful poodle mix who gets along with everyone. Her hypoallergenic coat makes her ideal for allergy-conscious adopters.',
  },
  {
    id: 'pet-010',
    name: 'Bear',
    breed: 'Newfoundland',
    age: 'puppy',
    size: 'large',
    description: 'A gentle giant puppy with the sweetest temperament.',
    imageUrls: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600',
    ],
    barkingLevel: 1,
    sheddingLevel: 5,
    trainingLevel: 1,
    energyLevel: 2,
    specialNeeds: false,
    behaviorTraits: ['calm', 'affectionate', 'social'],
    promptLabel: 'Fun fact',
    promptAnswer: 'I will outweigh you by next year',
    createdAt: '2026-01-05T10:00:00Z',
    compatibilityScore: 72,
    whyMatch: [
      'Gentle temperament despite large size',
      'Low barking is great for neighbors',
      'Will grow into a loving family dog',
    ],
    potentialChallenges: [
      'Will become very large (100-150 lbs)',
      'Extreme shedding requires constant grooming',
      'Puppy training needed from day one',
    ],
    aiSummary:
      'Bear is a lovable Newfoundland puppy who will grow into a gentle giant. He needs an owner prepared for his size and grooming needs.',
  },
];

const now = new Date();
const threeMonthsLater = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);

export const mockActiveMatch: ActiveMatch = {
  id: 'match-001',
  adopterId: 'adopter-001',
  petId: 'pet-001',
  status: 'in_foster',
  createdAt: now.toISOString(),
  updatedAt: now.toISOString(),
  stabilizationEndDate: threeMonthsLater.toISOString(),
  pet: mockPets[0],
  adopter: mockAdopter,
  daysInFoster: 14,
  stabilityScore: 72,
  bondScore: 68,
  incidentCount: 2,
  trainingAdherencePercent: 85,
};

export const mockStabilitySummary: StabilitySummary = {
  stabilityScore: 72,
  bondScore: 68,
  incidentCount: 2,
  trainingAdherencePercent: 85,
  trend: [45, 50, 55, 58, 62, 65, 68, 70, 72],
  daysRemaining: 76,
};

export const mockVisitSlots: VisitSlot[] = [
  { id: 'slot-1', date: '2026-02-25', startTime: '10:00', endTime: '11:00', available: true },
  { id: 'slot-2', date: '2026-02-25', startTime: '14:00', endTime: '15:00', available: true },
  { id: 'slot-3', date: '2026-02-26', startTime: '10:00', endTime: '11:00', available: true },
  { id: 'slot-4', date: '2026-02-26', startTime: '13:00', endTime: '14:00', available: false },
  { id: 'slot-5', date: '2026-02-27', startTime: '11:00', endTime: '12:00', available: true },
  { id: 'slot-6', date: '2026-02-27', startTime: '15:00', endTime: '16:00', available: true },
];

export const mockTrainingPlan: TrainingPlan = {
  id: 'tp-001',
  matchId: 'match-001',
  completionPercent: 25,
  premiumUpsellAvailable: true,
  weeks: Array.from({ length: 12 }, (_, weekIdx) => ({
    weekNumber: weekIdx + 1,
    title: [
      'Foundation & Trust',
      'Basic Commands',
      'Leash Training',
      'Socialization',
      'Impulse Control',
      'Advanced Commands',
      'Problem Solving',
      'Outdoor Confidence',
      'Alone Time Training',
      'Routine Solidification',
      'Stress Management',
      'Graduation Week',
    ][weekIdx],
    tasks: [
      {
        id: `task-${weekIdx * 3 + 1}`,
        weekNumber: weekIdx + 1,
        title: `Week ${weekIdx + 1} - Task 1`,
        description: [
          'Establish feeding schedule and designated spaces',
          'Practice "sit" command 10 times daily',
          'Short 5-minute leash walks around the block',
          'Introduce to one new person or dog this week',
          'Practice "leave it" with treats',
          'Teach "stay" for 30 seconds',
          'Address one specific behavioral concern',
          'Visit a new outdoor environment',
          'Practice 15-minute alone time',
          'Maintain consistent daily routine',
          'Practice calming exercises during triggers',
          'Complete a full training review session',
        ][weekIdx],
        completed: weekIdx < 3,
        dueDate: new Date(now.getTime() + weekIdx * 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: `task-${weekIdx * 3 + 2}`,
        weekNumber: weekIdx + 1,
        title: `Week ${weekIdx + 1} - Task 2`,
        description: 'Daily 10-minute bonding session with positive reinforcement',
        completed: weekIdx < 2,
      },
      {
        id: `task-${weekIdx * 3 + 3}`,
        weekNumber: weekIdx + 1,
        title: `Week ${weekIdx + 1} - Task 3`,
        description: 'Log observations and progress in the app',
        completed: weekIdx < 2,
      },
    ],
  })),
};

export const mockDailyCheckIn: DailyCheckIn = {
  id: 'dc-001',
  matchId: 'match-001',
  adopterId: 'adopter-001',
  dayRating: 'normal',
  stressSignals: false,
  createdAt: now.toISOString(),
};

export const mockWeeklyCheckIn: WeeklyCheckIn = {
  id: 'wc-001',
  matchId: 'match-001',
  adopterId: 'adopter-001',
  incidentCount: 1,
  ownerStress: 2,
  trainingAdherencePercent: 85,
  exerciseAdequacy: true,
  bond: 4,
  createdAt: now.toISOString(),
};
