/**
 * Firestore Seed Script
 *
 * Populates your Firestore database with 10 published pets,
 * a sample adopter, and a few visit slots.
 *
 * Prerequisites:
 *   1. npm install firebase-admin (dev dependency)
 *   2. Set GOOGLE_APPLICATION_CREDENTIALS to your service account key JSON path, OR
 *      Replace the projectId below and run from a gcloud-authenticated environment.
 *
 * Usage:
 *   npx ts-node scripts/seedFirestore.ts
 */

import * as admin from 'firebase-admin';

// Initialize with project ID — uses default credentials or service account key
admin.initializeApp({
  projectId: 'pawnder-ai', // <-- replace with your Firebase project ID
});

const db = admin.firestore();

// ─── Seed Pets (published, as shelterPets) ───

const SEED_PETS = [
  {
    name: 'Luna',
    species: 'dog',
    breed: 'Golden Retriever',
    sex: 'female',
    ageYears: 2,
    ageConfidence: 'certain',
    weightLbs: 65,
    sizeCategory: 'large',
    intakeDate: '2026-01-10',
    intakeSource: 'owner_surrender',
    adoptionFee: 250,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    // Health
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'high',
    mobilityLimit: 'none',
    petAllergies: '',
    // Temperament
    friendlinessAdults: 5,
    friendlinessKids: 4,
    friendlinessDogs: 4,
    friendlinessCats: 3,
    confidenceLevel: 4,
    touchSensitivity: 2,
    startleResponse: 2,
    vocalizationLevel: 2,
    preyDrive: 2,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 2,
    leashReactivity: 2,
    // Daily needs
    energyLevel: 4,
    exerciseMinPerDay: 60,
    enrichmentMinPerDay: 20,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 4,
    houseTraining: 'mostly_trained',
    leashTraining: 'mostly_trained',
    crateTraining: 'some_training',
    destructiveRisk: 2,
    escapeRisk: 1,
    sheddingLevel: 4,
    barkingLevel: 2,
    // Environment
    bestHousingTypes: ['house_medium', 'house_large'],
    yardRequirement: 'preferred',
    stairsOk: true,
    noiseTolerance: 3,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 3,
    needsExperiencedOwner: false,
    // Training
    trainingFocusAreas: ['leash_manners', 'recall'],
    trainingUrgency: 'moderate',
    estTrainingMinFirstMonth: 30,
    estWeeklyOngoing: 15,
    recommendedFormat: 'group',
    knownTriggers: [],
    managementTools: ['harness'],
    // Observations
    topStrengths: ['friendly', 'eager_to_please', 'gentle'],
    topChallenges: ['high_energy', 'heavy_shedding'],
    oneLineBlurb: 'A friendly golden who loves outdoor adventures.',
    structuredNotes: 'Luna is a joyful golden retriever who thrives with active families. She responds well to positive reinforcement and loves water.',
    idealAdopterNotes: 'Active household with yard. Someone who enjoys hiking or running.',
    // Media
    photoUris: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600',
    ],
    videoUris: [],
    coverPhotoIndex: 0,
    // Assessment
    assessorRole: 'staff',
    assessmentMethod: 'observation',
    observationHours: 20,
    overallConfidence: 4,
    completionPercent: 95,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Max',
    species: 'dog',
    breed: 'Labrador Mix',
    sex: 'male',
    ageYears: 4,
    ageConfidence: 'estimated',
    weightLbs: 70,
    sizeCategory: 'large',
    intakeDate: '2026-01-08',
    intakeSource: 'stray',
    adoptionFee: 200,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'medium',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 4,
    friendlinessDogs: 4,
    friendlinessCats: 3,
    confidenceLevel: 4,
    touchSensitivity: 2,
    startleResponse: 2,
    vocalizationLevel: 2,
    preyDrive: 2,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 3,
    leashReactivity: 1,
    energyLevel: 3,
    exerciseMinPerDay: 45,
    enrichmentMinPerDay: 15,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 5,
    houseTraining: 'fully_trained',
    leashTraining: 'fully_trained',
    crateTraining: 'some_training',
    destructiveRisk: 1,
    escapeRisk: 1,
    sheddingLevel: 3,
    barkingLevel: 2,
    bestHousingTypes: ['apartment', 'house_small', 'house_medium', 'house_large'],
    yardRequirement: 'not_needed',
    stairsOk: true,
    noiseTolerance: 4,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 2,
    needsExperiencedOwner: false,
    trainingFocusAreas: ['socialization'],
    trainingUrgency: 'low',
    estTrainingMinFirstMonth: 15,
    estWeeklyOngoing: 10,
    recommendedFormat: 'group',
    knownTriggers: [],
    managementTools: [],
    topStrengths: ['calm', 'affectionate', 'well_trained'],
    topChallenges: ['separation_anxiety'],
    oneLineBlurb: 'A gentle lab mix looking for his forever home.',
    structuredNotes: 'Max is a laid-back lab mix who already knows basic commands. Great with people and adapts easily.',
    idealAdopterNotes: 'Someone who works from home or has a flexible schedule.',
    photoUris: ['https://images.unsplash.com/photo-1529429617124-95b109e86bb8?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'staff',
    assessmentMethod: 'observation',
    observationHours: 15,
    overallConfidence: 4,
    completionPercent: 90,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Bella',
    species: 'dog',
    breed: 'Beagle',
    sex: 'female',
    ageYears: 0.5,
    ageConfidence: 'certain',
    weightLbs: 15,
    sizeCategory: 'small',
    intakeDate: '2026-01-12',
    intakeSource: 'rescue_transfer',
    adoptionFee: 300,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: false,
    spayNeuterStatus: 'scheduled',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'low',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 4,
    friendlinessDogs: 5,
    friendlinessCats: 3,
    confidenceLevel: 4,
    touchSensitivity: 1,
    startleResponse: 2,
    vocalizationLevel: 4,
    preyDrive: 4,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 3,
    leashReactivity: 3,
    energyLevel: 4,
    exerciseMinPerDay: 45,
    enrichmentMinPerDay: 20,
    pottyBreaksPerDay: 6,
    aloneTimeToleranceHrs: 2,
    houseTraining: 'minimal',
    leashTraining: 'minimal',
    crateTraining: 'none',
    destructiveRisk: 3,
    escapeRisk: 4,
    sheddingLevel: 2,
    barkingLevel: 4,
    bestHousingTypes: ['house_small', 'house_medium', 'house_large'],
    yardRequirement: 'required',
    stairsOk: true,
    noiseTolerance: 2,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 5,
    needsExperiencedOwner: false,
    trainingFocusAreas: ['house_training', 'leash_manners', 'recall'],
    trainingUrgency: 'high',
    estTrainingMinFirstMonth: 45,
    estWeeklyOngoing: 25,
    recommendedFormat: 'private',
    knownTriggers: ['small_animals'],
    managementTools: ['harness', 'crate'],
    topStrengths: ['playful', 'social', 'curious'],
    topChallenges: ['high_energy', 'vocal', 'escape_risk'],
    oneLineBlurb: 'An adorable beagle puppy with a curious personality.',
    structuredNotes: 'Bella is a spirited beagle puppy full of curiosity. She needs patient, consistent training.',
    idealAdopterNotes: 'Active person with a fenced yard. Experience with puppies helpful.',
    photoUris: ['https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'foster',
    assessmentMethod: 'foster',
    observationHours: 80,
    overallConfidence: 5,
    completionPercent: 92,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Charlie',
    species: 'dog',
    breed: 'French Bulldog',
    sex: 'male',
    ageYears: 5,
    ageConfidence: 'certain',
    weightLbs: 25,
    sizeCategory: 'small',
    intakeDate: '2026-01-09',
    intakeSource: 'owner_surrender',
    adoptionFee: 350,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: true,
    medsFrequency: 'Daily breathing support',
    specialDiet: false,
    knownConditions: [{ name: 'brachycephalic_syndrome', severity: 'moderate' }],
    groomingNeed: 'low',
    mobilityLimit: 'limited_exercise',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 4,
    friendlinessDogs: 3,
    friendlinessCats: 3,
    confidenceLevel: 3,
    touchSensitivity: 2,
    startleResponse: 2,
    vocalizationLevel: 1,
    preyDrive: 1,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 3,
    leashReactivity: 1,
    energyLevel: 2,
    exerciseMinPerDay: 20,
    enrichmentMinPerDay: 15,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 5,
    houseTraining: 'fully_trained',
    leashTraining: 'mostly_trained',
    crateTraining: 'fully_trained',
    destructiveRisk: 1,
    escapeRisk: 1,
    sheddingLevel: 2,
    barkingLevel: 1,
    bestHousingTypes: ['apartment', 'house_small', 'house_medium'],
    yardRequirement: 'not_needed',
    stairsOk: false,
    noiseTolerance: 4,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 3,
    needsExperiencedOwner: false,
    trainingFocusAreas: ['socialization'],
    trainingUrgency: 'low',
    estTrainingMinFirstMonth: 10,
    estWeeklyOngoing: 5,
    recommendedFormat: 'group',
    knownTriggers: [],
    managementTools: [],
    topStrengths: ['calm', 'affectionate', 'quiet'],
    topChallenges: ['health_needs', 'low_stamina'],
    oneLineBlurb: 'A charming Frenchie who loves snuggles.',
    structuredNotes: 'Charlie is a loving French Bulldog who prefers cuddles over cardio. Needs someone aware of brachycephalic health.',
    idealAdopterNotes: 'Low-activity home. Willing to manage ongoing health needs.',
    photoUris: ['https://images.unsplash.com/photo-1583337130417-13219ce0e39f?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'vet',
    assessmentMethod: 'vet_exam',
    observationHours: 5,
    overallConfidence: 5,
    completionPercent: 95,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Daisy',
    species: 'dog',
    breed: 'Border Collie',
    sex: 'female',
    ageYears: 2,
    ageConfidence: 'certain',
    weightLbs: 35,
    sizeCategory: 'medium',
    intakeDate: '2026-01-11',
    intakeSource: 'owner_surrender',
    adoptionFee: 275,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'medium',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 4,
    friendlinessKids: 3,
    friendlinessDogs: 3,
    friendlinessCats: 2,
    confidenceLevel: 4,
    touchSensitivity: 3,
    startleResponse: 3,
    vocalizationLevel: 3,
    preyDrive: 4,
    resourceGuardingRisk: 2,
    separationAnxietyRisk: 3,
    leashReactivity: 3,
    energyLevel: 5,
    exerciseMinPerDay: 90,
    enrichmentMinPerDay: 30,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 3,
    houseTraining: 'mostly_trained',
    leashTraining: 'some_training',
    crateTraining: 'some_training',
    destructiveRisk: 3,
    escapeRisk: 3,
    sheddingLevel: 3,
    barkingLevel: 3,
    bestHousingTypes: ['house_medium', 'house_large'],
    yardRequirement: 'required',
    stairsOk: true,
    noiseTolerance: 3,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 8,
    needsExperiencedOwner: true,
    trainingFocusAreas: ['impulse_control', 'recall', 'leash_manners'],
    trainingUrgency: 'high',
    estTrainingMinFirstMonth: 60,
    estWeeklyOngoing: 30,
    recommendedFormat: 'private',
    knownTriggers: ['small_animals', 'joggers'],
    managementTools: ['harness', 'long_line'],
    topStrengths: ['intelligent', 'athletic', 'loyal'],
    topChallenges: ['high_energy', 'herding_instinct', 'needs_mental_stimulation'],
    oneLineBlurb: 'A brilliant border collie looking for a job to do.',
    structuredNotes: 'Daisy is incredibly smart and needs mental stimulation as much as physical. Excels with owners who enjoy dog sports.',
    idealAdopterNotes: 'Experienced owner with large yard. Active lifestyle essential.',
    photoUris: ['https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'trainer',
    assessmentMethod: 'trainer_eval',
    observationHours: 10,
    overallConfidence: 5,
    completionPercent: 93,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Cooper',
    species: 'dog',
    breed: 'Australian Shepherd',
    sex: 'male',
    ageYears: 2,
    ageConfidence: 'estimated',
    weightLbs: 50,
    sizeCategory: 'medium',
    intakeDate: '2026-01-13',
    intakeSource: 'stray',
    adoptionFee: 250,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: false,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'high',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 4,
    friendlinessKids: 3,
    friendlinessDogs: 3,
    friendlinessCats: 2,
    confidenceLevel: 3,
    touchSensitivity: 3,
    startleResponse: 3,
    vocalizationLevel: 3,
    preyDrive: 3,
    resourceGuardingRisk: 2,
    separationAnxietyRisk: 2,
    leashReactivity: 3,
    energyLevel: 5,
    exerciseMinPerDay: 75,
    enrichmentMinPerDay: 25,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 3,
    houseTraining: 'mostly_trained',
    leashTraining: 'some_training',
    crateTraining: 'some_training',
    destructiveRisk: 3,
    escapeRisk: 2,
    sheddingLevel: 4,
    barkingLevel: 3,
    bestHousingTypes: ['house_medium', 'house_large'],
    yardRequirement: 'required',
    stairsOk: true,
    noiseTolerance: 3,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 6,
    needsExperiencedOwner: true,
    trainingFocusAreas: ['impulse_control', 'socialization', 'recall'],
    trainingUrgency: 'moderate',
    estTrainingMinFirstMonth: 45,
    estWeeklyOngoing: 20,
    recommendedFormat: 'private',
    knownTriggers: ['strangers'],
    managementTools: ['harness'],
    topStrengths: ['loyal', 'intelligent', 'athletic'],
    topChallenges: ['protective', 'heavy_shedding', 'needs_experienced_handler'],
    oneLineBlurb: 'A gorgeous Aussie with stunning blue eyes.',
    structuredNotes: 'Cooper is a loyal and intelligent Aussie who bonds deeply. Needs firm but gentle leadership.',
    idealAdopterNotes: 'Experienced owner with active lifestyle and fenced yard.',
    photoUris: ['https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'staff',
    assessmentMethod: 'observation',
    observationHours: 12,
    overallConfidence: 3,
    completionPercent: 88,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Milo',
    species: 'dog',
    breed: 'Cavalier King Charles',
    sex: 'male',
    ageYears: 10,
    ageConfidence: 'certain',
    weightLbs: 16,
    sizeCategory: 'small',
    intakeDate: '2026-01-07',
    intakeSource: 'owner_surrender',
    adoptionFee: 100,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: true,
    medsFrequency: 'Daily heart medication',
    specialDiet: true,
    specialDietType: 'Low-sodium cardiac diet',
    knownConditions: [{ name: 'heart_disease', severity: 'moderate' }],
    groomingNeed: 'medium',
    mobilityLimit: 'limited_exercise',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 4,
    friendlinessDogs: 3,
    friendlinessCats: 4,
    confidenceLevel: 3,
    touchSensitivity: 1,
    startleResponse: 2,
    vocalizationLevel: 1,
    preyDrive: 1,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 4,
    leashReactivity: 1,
    energyLevel: 1,
    exerciseMinPerDay: 15,
    enrichmentMinPerDay: 10,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 3,
    houseTraining: 'fully_trained',
    leashTraining: 'fully_trained',
    crateTraining: 'fully_trained',
    destructiveRisk: 1,
    escapeRisk: 1,
    sheddingLevel: 3,
    barkingLevel: 1,
    bestHousingTypes: ['apartment', 'house_small', 'house_medium', 'house_large'],
    yardRequirement: 'not_needed',
    stairsOk: false,
    noiseTolerance: 4,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 5,
    needsExperiencedOwner: false,
    trainingFocusAreas: [],
    trainingUrgency: 'low',
    estTrainingMinFirstMonth: 5,
    estWeeklyOngoing: 5,
    recommendedFormat: 'group',
    knownTriggers: [],
    managementTools: [],
    topStrengths: ['gentle', 'affectionate', 'well_trained'],
    topChallenges: ['health_needs', 'separation_anxiety'],
    oneLineBlurb: 'A sweet senior Cavalier looking for a quiet home.',
    structuredNotes: 'Milo is a gentle senior who has so much love left to give. Perfect for someone who values companionship.',
    idealAdopterNotes: 'Quiet home. Someone home often. Willing to manage cardiac care.',
    photoUris: ['https://images.unsplash.com/photo-1591160690555-5debfba0c36a?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'vet',
    assessmentMethod: 'vet_exam',
    observationHours: 3,
    overallConfidence: 5,
    completionPercent: 98,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Sadie',
    species: 'dog',
    breed: 'German Shepherd',
    sex: 'female',
    ageYears: 4,
    ageConfidence: 'certain',
    weightLbs: 70,
    sizeCategory: 'large',
    intakeDate: '2026-01-14',
    intakeSource: 'rescue_transfer',
    adoptionFee: 275,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: true,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'high',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 4,
    friendlinessKids: 3,
    friendlinessDogs: 2,
    friendlinessCats: 2,
    confidenceLevel: 4,
    touchSensitivity: 2,
    startleResponse: 2,
    vocalizationLevel: 3,
    preyDrive: 3,
    resourceGuardingRisk: 2,
    separationAnxietyRisk: 2,
    leashReactivity: 2,
    energyLevel: 4,
    exerciseMinPerDay: 60,
    enrichmentMinPerDay: 20,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 5,
    houseTraining: 'fully_trained',
    leashTraining: 'fully_trained',
    crateTraining: 'mostly_trained',
    destructiveRisk: 1,
    escapeRisk: 1,
    sheddingLevel: 5,
    barkingLevel: 3,
    bestHousingTypes: ['house_medium', 'house_large'],
    yardRequirement: 'required',
    stairsOk: true,
    noiseTolerance: 3,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 8,
    needsExperiencedOwner: true,
    trainingFocusAreas: ['socialization', 'confidence_building'],
    trainingUrgency: 'moderate',
    estTrainingMinFirstMonth: 30,
    estWeeklyOngoing: 15,
    recommendedFormat: 'private',
    knownTriggers: ['strangers'],
    managementTools: ['harness', 'muzzle'],
    topStrengths: ['loyal', 'obedient', 'protective'],
    topChallenges: ['wary_of_strangers', 'heavy_shedding'],
    oneLineBlurb: 'A loyal GSD who excels at obedience.',
    structuredNotes: 'Sadie is a devoted GSD who thrives with structure and clear leadership. Well-trained and incredibly loyal.',
    idealAdopterNotes: 'Experienced owner with confidence handling large breeds. Fenced yard.',
    photoUris: ['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'trainer',
    assessmentMethod: 'trainer_eval',
    observationHours: 8,
    overallConfidence: 4,
    completionPercent: 90,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Rosie',
    species: 'dog',
    breed: 'Poodle Mix',
    sex: 'female',
    ageYears: 2,
    ageConfidence: 'estimated',
    weightLbs: 18,
    sizeCategory: 'small',
    intakeDate: '2026-01-06',
    intakeSource: 'stray',
    adoptionFee: 225,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: false,
    spayNeuterStatus: 'done',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'high',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 5,
    friendlinessDogs: 5,
    friendlinessCats: 4,
    confidenceLevel: 4,
    touchSensitivity: 1,
    startleResponse: 2,
    vocalizationLevel: 2,
    preyDrive: 1,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 2,
    leashReactivity: 1,
    energyLevel: 3,
    exerciseMinPerDay: 30,
    enrichmentMinPerDay: 15,
    pottyBreaksPerDay: 4,
    aloneTimeToleranceHrs: 5,
    houseTraining: 'mostly_trained',
    leashTraining: 'mostly_trained',
    crateTraining: 'some_training',
    destructiveRisk: 1,
    escapeRisk: 1,
    sheddingLevel: 1,
    barkingLevel: 2,
    bestHousingTypes: ['apartment', 'house_small', 'house_medium', 'house_large'],
    yardRequirement: 'not_needed',
    stairsOk: true,
    noiseTolerance: 4,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 2,
    needsExperiencedOwner: false,
    trainingFocusAreas: ['leash_manners'],
    trainingUrgency: 'low',
    estTrainingMinFirstMonth: 15,
    estWeeklyOngoing: 10,
    recommendedFormat: 'group',
    knownTriggers: ['thunderstorms'],
    managementTools: ['thunder_shirt'],
    topStrengths: ['friendly', 'hypoallergenic', 'adaptable'],
    topChallenges: ['grooming_needs', 'storm_anxiety'],
    oneLineBlurb: 'A hypoallergenic poodle mix with a cheerful disposition.',
    structuredNotes: 'Rosie gets along with everyone. Her hypoallergenic coat makes her ideal for allergy-conscious adopters.',
    idealAdopterNotes: 'Any loving home. Great for first-time owners.',
    photoUris: ['https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'staff',
    assessmentMethod: 'observation',
    observationHours: 10,
    overallConfidence: 4,
    completionPercent: 88,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    name: 'Bear',
    species: 'dog',
    breed: 'Newfoundland',
    sex: 'male',
    ageYears: 0.75,
    ageConfidence: 'certain',
    weightLbs: 60,
    sizeCategory: 'large',
    intakeDate: '2026-01-05',
    intakeSource: 'owner_surrender',
    adoptionFee: 350,
    adoptionStatus: 'available',
    status: 'published',
    shelterId: 'seed-shelter-001',
    vaccineStatus: 'current',
    microchipped: false,
    spayNeuterStatus: 'scheduled',
    medsNeeded: false,
    specialDiet: false,
    knownConditions: [],
    groomingNeed: 'high',
    mobilityLimit: 'none',
    petAllergies: '',
    friendlinessAdults: 5,
    friendlinessKids: 5,
    friendlinessDogs: 4,
    friendlinessCats: 3,
    confidenceLevel: 4,
    touchSensitivity: 1,
    startleResponse: 1,
    vocalizationLevel: 1,
    preyDrive: 1,
    resourceGuardingRisk: 1,
    separationAnxietyRisk: 2,
    leashReactivity: 2,
    energyLevel: 2,
    exerciseMinPerDay: 30,
    enrichmentMinPerDay: 15,
    pottyBreaksPerDay: 5,
    aloneTimeToleranceHrs: 4,
    houseTraining: 'minimal',
    leashTraining: 'minimal',
    crateTraining: 'none',
    destructiveRisk: 2,
    escapeRisk: 1,
    sheddingLevel: 5,
    barkingLevel: 1,
    bestHousingTypes: ['house_medium', 'house_large'],
    yardRequirement: 'preferred',
    stairsOk: true,
    noiseTolerance: 4,
    singlePetOnly: false,
    compatibleWithKids: true,
    minimumKidAge: 2,
    needsExperiencedOwner: false,
    trainingFocusAreas: ['house_training', 'leash_manners', 'basic_obedience'],
    trainingUrgency: 'moderate',
    estTrainingMinFirstMonth: 30,
    estWeeklyOngoing: 15,
    recommendedFormat: 'group',
    knownTriggers: [],
    managementTools: ['crate'],
    topStrengths: ['gentle', 'calm', 'great_with_kids'],
    topChallenges: ['will_become_very_large', 'extreme_shedding', 'needs_puppy_training'],
    oneLineBlurb: 'A gentle giant puppy with the sweetest temperament.',
    structuredNotes: 'Bear is a lovable Newfoundland puppy who will grow into a gentle giant (100-150 lbs). Needs owner prepared for his size.',
    idealAdopterNotes: 'Home with space. Prepared for large breed needs and heavy grooming.',
    photoUris: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600'],
    videoUris: [],
    coverPhotoIndex: 0,
    assessorRole: 'staff',
    assessmentMethod: 'observation',
    observationHours: 8,
    overallConfidence: 4,
    completionPercent: 85,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    lastUpdated: admin.firestore.FieldValue.serverTimestamp(),
  },
];

// ─── Seed Visit Slots ───

const SEED_VISIT_SLOTS = [
  { petId: 'seed-pet-luna', date: '2026-03-01', startTime: '10:00', endTime: '11:00', available: true },
  { petId: 'seed-pet-luna', date: '2026-03-01', startTime: '14:00', endTime: '15:00', available: true },
  { petId: 'seed-pet-max', date: '2026-03-02', startTime: '10:00', endTime: '11:00', available: true },
];

// ─── Main ───

async function seed() {
  console.log('Seeding Firestore...');

  // Seed pets
  const petIds: string[] = [];
  for (const pet of SEED_PETS) {
    const slug = `seed-pet-${pet.name.toLowerCase()}`;
    petIds.push(slug);
    await db.collection('shelterPets').doc(slug).set(pet);
    console.log(`  Created pet: ${pet.name} (${slug})`);
  }

  // Update visit slot petIds to use actual pet IDs
  for (const slot of SEED_VISIT_SLOTS) {
    const ref = db.collection('visitSlots').doc();
    await ref.set(slot);
    console.log(`  Created visit slot: ${slot.date} ${slot.startTime}`);
  }

  // Seed sample adopter
  const sampleAdopter = {
    deviceId: 'seed-device-001',
    name: 'Alex Johnson',
    age: '28',
    phone: '555-123-4567',
    email: 'alex@example.com',
    zipCode: '90210',
    searchRadius: 25,
    housingType: 'house_medium',
    environment: 'suburban',
    householdSize: 2,
    kidsCount: 0,
    kidsAges: '',
    hoursAwayPerDay: 8,
    activityHoursPerWeek: 10,
    experienceLevel: 'intermediate',
    existingPetTypes: [],
    allergies: '',
    willingGroupClasses: true,
    willingPrivateTrainer: false,
    willingDailyExercises: true,
    trainingHoursPerWeek: 3,
    barkingTolerance: 3,
    sheddingTolerance: 4,
    trainingCommitment: 4,
    specialNeedsWilling: false,
    narrative1: 'I want a loyal companion for weekend hikes.',
    narrative2: 'I am patient and willing to invest time in training.',
    onboardingComplete: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  };
  await db.collection('adopters').doc('seed-adopter-001').set(sampleAdopter);
  console.log('  Created sample adopter: Alex Johnson');

  console.log('\nSeeding complete! Created:');
  console.log(`  ${SEED_PETS.length} pets`);
  console.log(`  ${SEED_VISIT_SLOTS.length} visit slots`);
  console.log('  1 sample adopter');
}

seed().catch(console.error);
